set -g mouse on
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
setw -g mode-keys vi

# STATUS BAR STYLING

## 'variables' for foreground and background
set -g @fg "#141414" #F87C63 #F54927 #1C2433
set -g @bg "#bb96cb"

## Status bar
set -g status-style "bg=#{@bg},fg=#{@fg}"

## Active window
set -g window-status-current-style "bg=#{@fg},fg=#{@bg}"

## Active window (with special style, no asterisk)
set -g window-status-current-format " #I:#W "


# VI MOTIONS
 
## Make `v` start selection (instead of Space)
bind-key -T copy-mode-vi v send -X begin-selection

## V = select entire line (linewise)
bind-key -T copy-mode-vi V send -X select-line

## Make `y` yank selection (instead of Enter) into clipboard (wayland)
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy"
